move files to sync subdirectory
dedis/debugtools pull request #3
Opened 2022-09-28 12:04 UTC by jbsv

First steps to prepare the debugtools package:
- move sources to a subdirectory
- complete the sync API to be aligned to the original

2022-09-28 14:38 UTC, jbsv commented on sync/mod.go
> +//	 SYNCLOG=info
🐛 in documentation: misaligned with code. need to fix that.

2022-09-28 14:38 UTC, jbsv commented on sync/mod.go
> +//   SYNCON=true
🐛 in documentation: misaligned with code. need to fix that.

2022-10-04 15:03 UTC, pierluca requested changes

2022-10-04 15:03 UTC, pierluca commented on README.md
> +system deadlock will fire off after a defined timeout.
I'd mention that it's a drop-in replacement for the sync standard library.

2022-10-04 15:03 UTC, pierluca commented on sync/once.go
> +// Once is an object that will perform exactly one action.
twice the comment :-)

2022-10-04 15:54 UTC, merged